[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://api.ghem.store"
  VITE_NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_BASE_URL = "https://api.ghem.store"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://api.ghem.store"

[context.branch-deploy.environment]
  VITE_API_BASE_URL = "https://api.ghem.store"
  VITE_NODE_ENV = "production" 